apiVersion: v1
kind: PersistentVolume
metadata:
  name: lemp-pv
spec:
  storageClassName: local-storage 
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #when persistent volume claim is deleted, data is deleted
  hostPath:
    path: "/data/lemp-pv"
    type: DirectoryOrCreate
