apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-pv
spec:
  storageClassName: local-storage 
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete #Retain #when persistent volume claim is deleted, data is deleted
  hostPath:
    path: "/data/project-pv"
    type: DirectoryOrCreate
