apiVersion: v1
kind: PersistentVolume
metadata:
  name: lemp-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete #when persistent volume claim is deleted, data is deleted
  hostPath:
    path: "/mnt/data"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pv-volume
# spec:
# #  storageClassName: local-storage
#   accessModes:
#   - ReadWriteOnce
#   ressources:
#     requests:
#       storage: 500Mi
