apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
spec:
  selector:
    app: telegraf
  type: ClusterIP
  ports:
  - port: 8094 
    targetPort: 8094 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-depl
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf 
    spec:
      serviceAccountName: telegraf-sa
      containers:
      - name: telegraf
        image: telegraf-service:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: service-configmap
        ports:
        - containerPort: 8094
        volumeMounts:
        - name: telegraf-endpoint
          mountPath: "/var/run/docker.sock"
      restartPolicy: Always
      volumes:
      - name: telegraf-endpoint
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-sa
  labels:
    app: telegraf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf
subjects:
- kind: ServiceAccount
  name: telegraf-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
