apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-depl
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps 
        image: ftps-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 10090
        - containerPort: 10091
        - containerPort: 10092
        - containerPort: 10093
        - containerPort: 10094
        - containerPort: 10095
        - containerPort: 10096
        - containerPort: 10097
        - containerPort: 10098
        - containerPort: 10099
        - containerPort: 10100
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - name: ftp-20
    port: 20
  - name: ftp-21
    port: 21
  - name: ftp-10090
    port: 10090
  - name: ftp-10091
    port: 10091
  - name: ftp-10092
    port: 10092
  - name: ftp-10093
    port: 10093
  - name: ftp-10094
    port: 10094
  - name: ftp-10095
    port: 10095
  - name: ftp-10096
    port: 10096
  - name: ftp-10097
    port: 10097
  - name: ftp-10098
    port: 10098
  - name: ftp-10099
    port: 10099
  - name: ftp-10100
    port: 10100
