apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: grafana 
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 3000 
    targetPort: 3000 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-depl
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana 
    spec:
      containers:
      - name: grafana
        image: grafana-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000 
        envFrom:
        - configMapRef:
            name: service-configmap
      restartPolicy: Always
        # env:
        #   - name: MYSQL_ROOT_PASSWORD
        #     valueFrom:
        #       secretKeyRef:
        #         name: ftservice-secrets
        #         key: mysql-root-pwd
