apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-depl
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin 
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000 
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: phpmyadmin 
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 5000 
    targetPort: 5000 
