apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    app: nginx	#key value paire that will stick to it - this will be used by the service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template: #config file inside of config file.. = pod blueprint
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
	annotations:
		metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
