apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
   app: nginx	#key value paire that will stick to it - this will be used by the service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template: #config file inside of config file.. = pod blueprint
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx_service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
#  ports:
#    - protocol: TCP
#      port: 443
#      targetPort: 443
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
#      port: 80
#      targetPort: 80
